name: skbwtrainer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.6.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  loading_animation_widget: ^1.3.0
  fl_chart: ^0.70.0
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: Retroica
      fonts:
        - asset: fonts/retroica/Retroica.ttf

    - family: Brigade
      fonts:
        - asset: fonts/brigade/Brigade.ttf

    - family: Elegance
      fonts:
        - asset: fonts/rounded_elegance/Rounded_Elegance_Regular.otf
